.TH "ws_close" "3" "Release 0.0.1" "Carnegie Mellon University" "Wholeslide Library"
.SH "NAME"
.LP 
\fBws_close\fR \- Close a whole slide image
.SH "SYNTAX"
.LP 
#include <wholeslide.h>
.LP 
void \fBws_close\fR(wholeslide_t *\fIwsd\fP)
.SH "ARGUMENTS"
.LP 
.TP 
\fIwsd\fP
Specifies the wholeslide_t object.
.TP 
.SH "DESCRIPTION"
.LP 
\fBws_close\fR closes a whole slide image.
.SH "SEE ALSO"
.LP 
ws_open(3) ws_read_region(3) ws_stat(3) ws_prefetch_hint(3)
