#!/usr/bin/python

from pathlib import Path
from urllib.parse import urlencode

import yaml

dir = Path(__file__).parent
with open(dir / 'README.md', 'w') as fh:
    fh.write('<!-- Generated by mkmaintainer.py; do not edit -->\n\n')
    fh.write('## Maintainer issue templates\n\n')
    for path in sorted(dir.iterdir()):
        if path.name == 'README.md' or path.suffix != '.md':
            continue
        _, front, body = path.read_text().split('---\n', 2)
        info = yaml.safe_load(front)
        args = urlencode(
            {
                'title': info['title'],
                'body': body.strip(),
                'labels': ','.join(info.get('labels', [])),
            }
        )
        url = f"https://github.com/{info['repo']}/issues/new?{args}"
        fh.write(f"- [{info['link-text']}]({url})\n")
